# yaml-language-server: $schema=../../../schemas/folder.schema.json

name: Production
tag_bindings:
  environment: environment/production
iam_by_principals:
   "group:lds-team-product-admins@littledragonsoftware.com":
     - roles/editor
   "group:lds-team-product@littledragonsoftware.com":
     - roles/viewer
